services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - NVIDIA_VISIBLE_DEVICES=0,1
    volumes:
      - open-webui:/app/backend/data
    networks:
      - internal
      - caddy-net

volumes:
  open-webui:

networks:
  internal:
    external: true
  caddy-net:
    external: true
