'1722708641187':
  alias: Find My Phone
  sequence:
  - service: notify.mobile_app_azael_s24u
    metadata: {}
    data:
      message: Home Assistant is searching your phone!
      data:
        ttl: 0
        priority: high
        channel: alarm_stream
