# n8n/docker-compose.yml
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    environment:
      - TZ=America/New_York # Set your timezone
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_SECURE_COOKIE=false
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678
    volumes:
      - ./data:/home/node/.n8n
    networks:
      - internal
      - caddy-net

networks:
  internal:
    external: true
  caddy-net:
    external: true
