services:
  jupyter-pytorch:
    image: nvcr.io/nvidia/pytorch:23.10-py3  # NVIDIA PyTorch (optimized for CUDA)
    container_name: jupyter-pytorch
    restart: unless-stopped
    ipc: "host"  # Optimizes shared memory for ML workloads
    shm_size: "8G"  # Ensures enough memory for Jupyter processes
    cap_add:
      - SYS_PTRACE  # Allows debugging tools like `gdb`
    security_opt:
      - seccomp=unconfined  # Allows unrestricted system calls (needed for PyTorch debugging)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Use all available GPUs
              capabilities: [gpu]
    volumes:
      - ./notebooks:/workspace  # Mounts notebook directory
    env_file:
      - .env
    command:
      - bash
      - "-c"
      - |
        pip install --upgrade pip && \
        pip install langchain langchain-ollama && \
        exec jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root \
        --NotebookApp.password="${JUPYTER_PASSWORD}"
    networks:
      - default
      - caddy-net

networks:
  default:
  caddy-net:
    external: true
